### ISSUE TITLE
DL3020 fires on ADD ./files/my.tar.gz

### ISSUE THREAD

**Issue by LudwigHoff** [lukasmartinelli/hadolint#16]
Maybe a list of known archive extensions could be whitelisted.

Love the tool by the way.  Only raising this cos the page asks for issues to be raised.

**Comment by lukasmartinelli** [comment]
Uups now that was a real bug. Unit test didn't catch it. Thanks.

**Comment by lukasmartinelli** [comment]
Seems to be fixed. 

![kk8ghlbuzk](https://cloud.githubusercontent.com/assets/1288339/12478894/1297cbaa-c038-11e5-8d65-709ea9040abb.gif)
