### ISSUE TITLE
DL3008 false positive

### ISSUE THREAD

**Issue by nixlike** [lukasmartinelli/hadolint#19]
Hi Lukas,

Dockerfile: 

FROM ubuntu:15.10
MAINTAINER Oleksii Dzhulai nixlike@gmail.com

WORKDIR /tmp

RUN sed -i 's/http:\/\/archive.ubuntu.com\/ubuntu\//mirror:\/\/mirrors.ubuntu.com\/mirrors.txt/' /etc/apt/sources.list
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install --no-install-recommends -y \
        python-demjson=2.2.2* \
        wget=1.16.1* \
        git=1:2.5.0* \
        ruby=1:2.1.* \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*
RUN gem install ruby-lint

Output:
  /bin/sh -c docker\ run\ --rm\ -i\ lukasmartinelli/hadolint\ \<\ buildcont/Dockerfile
       L7 DL3008 Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`

Please advise

Thanks

**Comment by lukasmartinelli** [comment]
Yes I knew there were some gotchas in parsing the `apt` command. I probably need to strip the options aways. Thanks for the report.

btw. do you know whether `apt-get clean` is a Dockerfile best practice?
Seems like a good option to have.

**Comment by lukasmartinelli** [comment]
It seems to work on http://hadolint.lukasmartinelli.ch. I fixed some other parsing stuff perhaps that helped.

![pngaj0pkhm](https://cloud.githubusercontent.com/assets/1288339/12480436/9c91c928-c042-11e5-9618-20bd7223318d.gif)

**Comment by nixlike** [comment]
> btw. do you know whether apt-get clean is a Dockerfile best practice?
> Seems like a good option to have.

Docker recommends it
https://docs.docker.com/engine/articles/dockerfile_best-practices/

Thanks for fixing! I've pulled latest, when docker image will include the fix ?
