### ISSUE TITLE
Parse fails with multiline comments

### ISSUE THREAD

**Issue by jottr** [lukasmartinelli/hadolint#21]
I have a multiline comment like this in my `Dockerfile`:

```bash
# line 1
# line 2
RUN apt-get update ...
```
which results in an`unexpected "\n"` error.

**Comment by lukasmartinelli** [comment]
Can you post a full Dockerfile?

I cannot create a regression in the test suite.

https://github.com/lukasmartinelli/hadolint/blob/master/src/Test.hs#L41-L42
