### ISSUE TITLE
Parsing fails when environment variables are set as "ENV <key> <value>"

### ISSUE THREAD

**Issue by chk1** [lukasmartinelli/hadolint#22]
According to the [docs](https://docs.docker.com/engine/reference/builder/#env) there are two ways to use ENV, however: 

This works: `ENV <key>=<value>`

This does not and will cause the parser to fail: `ENV <key> <value>`

```
Object {error: ""<string>" (line 5, column 14):↵unexpected "\n""}
editor.js:17 Uncaught TypeError: Cannot read property 'message' of undefined
```

Using the example from a recent pull request:

```
FROM debian:stable
MAINTAINER Foo <foo@foo>
ENV foo Hello World
```

Other things such as putting random letters in Dockerfiles will also trigger a Javascript error, again line 17 from editor.js is referenced.

```
FROM debian:stable
MAINTAINER Foo <foo@foo>
ENV foo="Hello World"
asdf
```

**Comment by lukasmartinelli** [comment]
This should work. Which is important.
https://github.com/lukasmartinelli/hadolint/blob/master/src/Test.hs#L31

```dockerfile
ENV foo bar
```

But assigning `Hello World` to `foo` without quoting does not work yet.  I am not sure whether that is really valid. If you do `export foo Hello World` you will also only get the `Hello` stored in the `foo` variable which makes the `foo Hello World` assignment a bad practice.

```dockerfile
ENV foo Hello World
```
