### ISSUE TITLE
We should have an ability to ignore some rules.

### ISSUE THREAD

**Issue by niksite** [lukasmartinelli/hadolint#24]
E.g. `hadolint -i --ignore=DL3008` would be much appreciated.

**Comment by lukasmartinelli** [comment]
:+1:

**Comment by timgriffiths** [comment]
Would be better if you could add a comment in the dockerfile directly above what you wanted to ignore so it was clear to all users. Ie
#DL3008 ignoring because abc

**Comment by bootstraponline** [comment]
:+1:

**Comment by jmreicha** [comment]
I'd like to see something like @timgriffiths mentioned.  I think something similar to how Shellcheck  works would be nice.

```
# hadolint disable=DL3006
FROM ubuntu
```

For example.

**Comment by ye** [comment]
I, too, agree with @timgriffiths that Dockerfile line comment is a better and more flexible way to ignore rules than using command line argument(s). The difference lies in the fact that you can cherry picking the local scope where certain rule(s) should be ignored while maintaining the check on other places. If we are implementing a command line argument, it's less flexible as the rule ignore will be applied globally.

This line comment ignore rule practice is also used in other linters like [pylint](https://docs.pylint.org/en/latest/faq.html#is-it-possible-to-locally-disable-a-particular-message)

**Comment by lukasmartinelli** [comment]
> I, too, agree with @timgriffiths that Dockerfile line comment is a better and more flexible way to ignore rules than using command line argument(s). The difference lies in the fact that you can cherry picking the local scope where certain rule(s) should be ignored while maintaining the check on other places. If we are implementing a command line argument, it's less flexible as the rule ignore will be applied globally.

I like the comment version more as well. It is a bit more tricky to implement since it is then part of the AST and it is the first time that two Dockerfile instructions would relate to each other. The `RUN` instruction would only **not** be tested against the rule if a `COMMENT` instruction one line above exists and has it disabled.

To not get lost with this I will start with a** command line version** since with this I can just filter out all lint results from that rule. Build an MVP first 😁

**Comment by ye** [comment]
Excited for v1.1, can't wait! 

Any indicator of timeframe for v1.1 to be released @lukasmartinelli ? Without the ignore rule feature, my CI build is currently failing... :(

![screen shot 2016-08-18 at 1 41 16 pm](https://cloud.githubusercontent.com/assets/133924/17784226/b76241f4-6549-11e6-9128-ed89942c2852.png)

**Comment by lukasmartinelli** [comment]
@ye Sorry never followed up - this should be included in the latest releases
https://github.com/lukasmartinelli/hadolint/releases
