### ISSUE TITLE
False Alarm DL3000 Use absolute WORKDIR

### ISSUE THREAD

**Issue by christianwoehrle** [lukasmartinelli/hadolint#28]
This 
WORKDIR $ENVIRONMENTPATH

leads to DL3000 Use absolute WORKDIR
Look like the checks is for leading "/" only?

**Comment by lukasmartinelli** [comment]
Thank. Didn't know you can use env vars in `WORKDIR`. Need to change the implementation.

**Comment by lukasmartinelli** [comment]
Fixed together with #30.
