### ISSUE TITLE
DL3000 not honouring the exception part

### ISSUE THREAD

**Issue by vishalvsh1** [lukasmartinelli/hadolint#30]
I have Dockerfile which has following syntax
```
  ENV work /raven
  WORKDIR ${work}
```

when i tried online version to check, it is throwing DL3000 error. Ideally as per document this comes as part of exception because work is already set in ENV.

**Comment by lukasmartinelli** [comment]
Thanks alot. Good description.

I don't backtrack the `$work` to the work env variable yet.
I now implemented that you can use references in `WORKDIR` which without triggering DL300.

**Comment by vishalvsh1** [comment]
Thanks a lot for this, Happy to see this. Great work.
