### ISSUE TITLE
Online demo at http://hadolint.lukasmartinelli.ch/ broken (404 and CORS errors)

### ISSUE THREAD

**Issue by dserodio** [lukasmartinelli/hadolint#37]
When I click on Lint in http://hadolint.lukasmartinelli.ch/ it sends a POST to http://api.hadolint.lukasmartinelli.ch/dockerfile which fails with a 404 error, followed by this error in the Console (Firefox):

    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://api.hadolint.lukasmartinelli.ch/dockerfile. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

**Comment by DJviolin** [comment]
Same for me in latest Firefox, Chrome.

**Comment by lukasmartinelli** [comment]
> Same for me in latest Firefox, Chrome and IE.

Up and running again. Will keep an eye on it in the future!

http://hadolint.lukasmartinelli.ch/

Actually I didn't even now where it was running ;)
Set it up again (running the docker image `lukasmartinelli/hadolint:api`. App is sometimes slow because server is tight on ressources.
