### ISSUE TITLE
Allow to pass a set of rules to ignore

### ISSUE THREAD

**Issue by dokempf** [lukasmartinelli/hadolint#40]
It would be nice if it would be possible to pass a set of rules that should be ignored by the linter. Compare to python, where pep8 is an accepted standard, but almost every project defines 2-3 well-thought-of exceptions. I cannot simply ignore the output, as I want to use hadolint in a CI system.

FWIW, the rule that I disagree with is DL3008.

**Comment by ye** [comment]
This is a duplicate of #24
