### ISSUE TITLE
Rule suggestion: Recommend `SHELL ["/bin/bash", "-c"]` instead of `RUN /bin/bash -c "..."` 

### ISSUE THREAD

**Issue by backus** [lukasmartinelli/hadolint#58]
Docker 1.12 has a [`SHELL`](https://docs.docker.com/engine/reference/builder/#/shell) instruction which is much nicer than writing `/bin/bash -c "..."` everywhere

**Comment by lukasmartinelli** [comment]
Wow a lot of new instructions. I thought they froze the syntax...

But shell does more. It is another instruction that modifies the subsequent instructions..
From what I read this is meant to substitute the default shell? Like switch from bash to powershell?
Probably mostly useful for windows folks.

I have to think how to deal with the new instructions and parser directives. Will probably just skip them for now so that we don't have parse errors with newer Dockerfiles.

**Comment by backus** [comment]
> I have to think how to deal with the new instructions and parser directives. Will probably just skip them for now so that we don't have parse errors with newer Dockerfiles.

Yeah I think that is a good first step.

> But shell does more. It is another instruction that modifies the subsequent instructions..
From what I read this is meant to substitute the default shell? Like switch from bash to powershell?
Probably mostly useful for windows folks.

Well a more conservative rule could detect something like this and recommend `SHELL` I'm sure: https://github.com/dkubb/dockerfiles/blob/master/alpine-ruby/Dockerfile#L22

**Comment by lukasmartinelli** [comment]
> Well a more conservative rule could detect something like this and recommend SHELL I'm sure: https://github.com/dkubb/dockerfiles/blob/master/alpine-ruby/Dockerfile#L22

Oh that is a nice idea! I would implement that.

If you'd like that you can open a new issue for that and perhaps even write a wiki entry.

**Comment by backus** [comment]
> If you'd like that you can open a new issue for that and perhaps even write a wiki entry.


I could try to help out. If you would like a separate issue for this then I'll open it. I'll hold off on writing a wiki entry until there is an implementation so I don't confuse others. Right now I'm trying to build the project locally but I've only fiddled with Haskell in the past so I'm moving at a snails pace.

**Comment by backus** [comment]
Extracted the second `SHELL` rule proposal to #59

**Comment by backus** [comment]
> perhaps even write a wiki entry.

@lukasmartinelli I've added the wiki page now: https://github.com/lukasmartinelli/hadolint/wiki/DL4005

On an unrelated note: do you think this issue should be closed now? I'm not clear on what further rules you'd like to add for `SHELL`
