### ISSUE TITLE
DL3009 Not recognizing clean up in multiple RUN statements

### ISSUE THREAD

**Issue by mydevbox** [lukasmartinelli/hadolint#63]
I ran the linter on my Dockerfile and received the DL3009 warning. After looking at the docs I found that my Dockerfile has all of the steps needed to satisfy the rule however, they occur in different RUN statements. It would be great if the linter recognized this.

`RUN  apt-get update \`
`  && DEBIAN_FRONTEND=noninteractive \`
`     apt-get install --no-install-recommends -y \`
`        build-essential \`
`        git \`
`  && apt-get clean`
.
.
.
`RUN rm -rf /var/lib/apt/lists/* \`
`            /tmp/* \`
`            /var/tmp/*`

**Comment by lukasmartinelli** [comment]
> RUN rm -rf /var/lib/apt/lists/* \
> /tmp/* \
> /var/tmp/*

I am not sure whether I am right, please correct me. But to my knowledge through the layered file system you don't save space like that.

You have just created a second layer that removes the bytes in the previously added layer. But that doesn't decrease the total.

**Comment by mydevbox** [comment]
I just tested and the way that I have it written does NOT reduce the size of the final image but including it on the same RUN as the apt-get does. I was not aware of that and have corrected by Dockerfile. Thanks!
