### ISSUE TITLE
DL3020 Use COPY instead of ADD for files and folders: False Positive

### ISSUE THREAD

**Issue by j3p0uk** [lukasmartinelli/hadolint#68]
When extracting a compressed tar file with .tgz suffix, falsely identifies as requiring COPY instead.
:3 DL3020 Use COPY instead of ADD for files and folders

Need to add all suffixes from Wikipedia Tar Suffixes

Git sha1: 22e1eef5815e1e970c2b488998266505fe5d300b

**Comment by lukasmartinelli** [comment]
tgz should be supported though: https://github.com/lukasmartinelli/hadolint/blob/master/src/Hadolint/Rules.hs#L279

**Comment by j3p0uk** [comment]
Hmm, that is strange.  I will retest to verify behaviour.  Closing this PR and will open a new one if I see it again.

**Comment by j75** [comment]
I have the same problem, it didn't realize that the source is an URL, thus `COPY` dose not work.
