### ISSUE TITLE
Question re: DL3003 Use WORKDIR to switch to a directory.

### ISSUE THREAD

**Issue by r4j4h** [lukasmartinelli/hadolint#70]
I have a Dockerfile where I need to manually install some software using a command like this:

```
# Install Python 2.7
WORKDIR /tmp/
RUN wget --no-check-certificate "https://www.python.org/ftp/python/2.7.6/Python-2.7.6.tar.xz" \
 && tar xf Python-2.7.6.tar.xz \
 && cd Python-2.7.6 \
 && ./configure --prefix=/usr/local \
 && make && make altinstall \
 && cd .. \
 && rm -rf Python-2.7.6 \
 && rm -rf Python-2.7.6.tar.xz
```

Is the suggestion really to turn that into

```
# Install Python 2.7
WORKDIR /tmp/
RUN wget --no-check-certificate "https://www.python.org/ftp/python/2.7.6/Python-2.7.6.tar.xz" \
 && tar xf Python-2.7.6.tar.xz
WORKDIR /tmp/python2.7-installation/Python-2.7.6
RUN ./configure --prefix=/usr/local \
 && make && make altinstall
WORKDIR /tmp/python2.7-installation/
RUN rm -rf Python-2.7.6 \
 && rm -rf Python-2.7.6.tar.xz
```

While arguably more readable, that more than doubles the amount of layers created. So I just wanted to see what your thoughts were on commands like these. :)

**Comment by lukasmartinelli** [comment]
> I have a Dockerfile where I need to manually install some software using a command like this:

Sometimes you don't get around a `cd`. But most commands actually support absolute paths ( so often times you don't need `cd`).
And when you do, you can use `cd` in a subshell so at least the context is only for that command.

```
(cd $home; [ -e $FILE ] && less $FILE)
````

However, generally this is a rule with too many false negatives. It should more be a hint.
And I myself also fall back frequently to the pattern you showed above.

**Comment by r4j4h** [comment]
Thanks for the quick feedback! I do think it is a helpful rule/hint to have.

I will implement the subshell suggestion as that seems very useful!

**Comment by blueyed** [comment]
Using the subshell approach still triggers DL3003, doesn't it?

My use case is `cd /usr/bin && ln -s python3 python && ln -s pip3 pip`, which is clearer than `ln -t /usr/bin -s python3 python && ln -t /usr/bin -s pip3 pip` (and busybox's `ln` does not appear to support `-t` anyway).

**Comment by lorenzo** [comment]
Yeah, it does trigger in a su shell. i would love to come up with a new logic for this rule, but I haven’t thought through when using cd is acceptable.

I can investigate if it is possible to detect a sub shell

**Comment by ThibF** [comment]
DL3003 is close in principle to [SC2164](https://github.com/koalaman/shellcheck/wiki/SC2164).
In summary, both rules says : `Don't cd without subshell`.

DL3003 rationale: 

> Only use cd in a subshell. Most commands can work with absolute paths and it in most cases not necessary to change directories. Docker provides the WORKDIR instruction if you really need to change the current working directory.

But currently Shellcheck is already checking for bad use of `cd` without subshell.
It seems also more relevant to use Shellcheck than Hadolint for detecting this kind of usage.

Maybe DL3003 should be removed from the rules ?

**Comment by vstavrinov** [comment]
abuild requires APKBUILD in current directory and subshell doesn't prevent DL3003 warning
