### ISSUE TITLE
MAINTAINER is deprecated. LABEL is recommended instead

### ISSUE THREAD

**Issue by ttres** [lukasmartinelli/hadolint#71]
The `MAINTAINER` command [will be deprecated](https://github.com/docker/docker/blob/master/docs/deprecated.md#maintainer-in-dockerfile).

The existence, instead of the inexistence, should be an error.

**Comment by EvgenyOrekhov** [comment]
It is already deprecated in Docker 1.13.0.

**Comment by lukasmartinelli** [comment]
@ttres @EvgenyOrekhov
I changed the rule `DL4000` in the Wiki https://github.com/lukasmartinelli/hadolint/wiki/DL4000 
and the code 9b0ba8bc529e0b205ba3c622d93c227044ababbb

Also deprecated the maintainer address rule https://github.com/lukasmartinelli/hadolint/wiki/DL3012
and in code 73d6f2fa5dde210499df437cac44df7cd4b67328
