### ISSUE TITLE
when i am trying to build hadolint  getting this issue

### ISSUE THREAD

**Issue by daashayani** [lukasmartinelli/hadolint#78]
[root@dockerdst hadolint]# stack build
hadolint-1.2.1.0: build (lib + exe)
Preprocessing library hadolint-1.2.1.0...
Cabal-simple_mPHDZzAJ_1.22.5.0_ghc-7.10.3: can't find source for
Hadolint/Rules in src,
.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/autogen

--  While building package hadolint-1.2.1.0 using:
      /root/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.22.5.0_ghc-7.10.3 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.5.0 build lib:hadolint exe:hadolint --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1

**Comment by zemanlx** [comment]
@daashayani Can you give me more information? 

BTW You can look at our [Dockerfile](https://github.com/lukasmartinelli/hadolint/blob/master/Dockerfile) how to build hadolint from scratch on Linux.

**Comment by zemanlx** [comment]
No response, closing.
