### ISSUE TITLE
Display Dockerfile path when showing the results

### ISSUE THREAD

**Issue by ye** [lukasmartinelli/hadolint#9]
Currently, only line numbers are printed out when there is a rule violation detected. It would be great to have the path to the Dockerfile examined printed out as well, just like most of other linters/compilers do.
That way, we can write a simple bash script to lint a whole bunch of Dockerfiles and the results would make more sense as to while violation is pertaining to which Dockerfile.
Additionally, `hadolint` perhaps can take a directory and find the Dockerfiles in it and show results altogether instead of having to run it one Dockerfile at a time.

**Comment by lukasmartinelli** [comment]
> Currently, only line numbers are printed out when there is a rule violation detected. It would be great to have the path to the Dockerfile examined printed out as well, just like most of other linters/compilers do.
> That way, we can write a simple bash script to lint a whole bunch of Dockerfiles and the results would make more sense as to while violation is pertaining to which Dockerfile.
> Additionally, hadolint perhaps can take a directory and find the Dockerfiles in it and show results altogether instead of having to run it one Dockerfile at a time.

That all makes a whole lot of sense! The CLI version is very basic, I want to implement multiple formatters to support better output.

Actuall didn't think people would use the CLI version because installing something with Haskell is kind of difficult.

**Comment by ye** [comment]
@lukasmartinelli since there is no GUI, how else would you expect people to use `hadolint` other than CLI? ;) In fact, you'd be surprised a lot of us on Github know how to compile code into binaries and know a thing or two about Unix and command line!

**Comment by lukasmartinelli** [comment]
Fixed by #35.
