### ISSUE TITLE
MAINTAINER is deprecated

### ISSUE THREAD

**Issue by yukiisbored** [lukasmartinelli/hadolint#93]
It looks like [DL4000](https://github.com/lukasmartinelli/hadolint/wiki/DL4000) is conflicting with the latest Dockerfile reference which states [`MAINTAINER` is deprecated](https://docs.docker.com/engine/reference/builder/#maintainer-deprecated).

I think DL4000 behavior needs to be changed to ensure `MAINTAINER` is not used and replace it with `LABEL maintainer=`.

**Comment by matteocng** [comment]
hi @yukiisbored, I've noticed this issue too by using the`Docker` image (latest successful build: 2016-09-30, before [the fix](https://github.com/lukasmartinelli/hadolint/commit/73d6f2fa5dde210499df437cac44df7cd4b67328)). This was fixed in #71 and works (`Dockerfile DL4000 MAINTAINER is deprecated`) when building `hadolint` locally,  installing it with `brew` or downloading the release binary from GitHub. Maybe we could try building the `Docker` image with `Travis` to keep it more up-to-date?

**Comment by yukiisbored** [comment]
@matteocng ah, yeah I was using the docker image to use it. I think it's preferable to build the docker image with Travis to keep it up to date since right now it's lacking behind.

**Comment by sobolevn** [comment]
Installed it with `brew`. 

```
» hadolint --version
Haskell Dockerfile Linter v1.2.1
```

I have an explicit label in my `Dockerfile`:

```
LABEL maintainer="Nikita Sobolev <sobolevn@wemake.services>"
```

But it results in error:

```
» hadolint Dockerfile 
Dockerfile DL4000 Specify a maintainer of the Dockerfile
```

**Comment by zemanlx** [comment]
@sobolevn @yukiisbored @matteocng I have tested it now with build from the master branch and it works. Can you please retest, if it is fixed for you and let me know?

Docker image is automatic build in Docker Hub, `lukasmartinelli/hadolint:lastest` is image of current commit in `master` branch.

Not sure how it works with `brew` as I do not have Mac.

This is my test of `maintainer`:
 
```bash
$ hadolint --version
Haskell Dockerfile Linter v1.2.2-30-gaa3db87
```

Old `MAINTAINER`

```bash
$ cat Dockerfile.93.1
FROM issue:93
MAINTAINER zemanlx me@home.ea

$ hadolint Dockerfile.93.1
Dockerfile.93.1 DL4000 MAINTAINER is deprecated
$
```

Use a maintainer in `LABEL`

```bash
$ cat Dockerfile.93.2
FROM issue:93
LABEL maintainer="Nikita Sobolev <sobolevn@wemake.services>"

$ hadolint Dockerfile.93.2
$
```

**Comment by yukiisbored** [comment]
@zemanlx Okay it works now^^

```
[yuki:~] % docker run --rm -i lukasmartinelli/hadolint < Dockerfile
Unable to find image 'lukasmartinelli/hadolint:latest' locally
latest: Pulling from lukasmartinelli/hadolint
8da261274716: Pull complete 
89824c634ee9: Pull complete 
Digest: sha256:45e2507590acaa2a06d06d43e38cc14babe6894f96f9fdc743960ac1ca67dc8b
Status: Downloaded newer image for lukasmartinelli/hadolint:latest
/dev/stdin DL4000 MAINTAINER is deprecated
```
