### ISSUE TITLE
Need rule to exclude syntax

### ISSUE THREAD

**Issue by DevOps575** [lukasmartinelli/hadolint#94]
Hi,

I am having a Dockerfile instruction LABEL with below values:
LABEL com.abc.image.name='xyz'\
com.abc.image.tag='latest'

but when I run the command: hadolint Dockerfile I get the below error:

unexpected '='
expecting space, "\t", "ONBUILD", "FROM", "COPY", "RUN", "WORKDIR", "ENTRYPOINT", "VOLUME", "EXPOSE", "ENV", "ARG", "USER", "LABEL", "STOPSIGNAL", "CMD", "MAINTAINER", "ADD", "#" or end of input

Please help me how I can bypass this check...

Thanks

**Comment by zemanlx** [comment]
@DevOps575 If you want to set more labels in one `LABEL` you need to use backslash `\` at the end of  continuing line
```
cat Dockerfile; hadolint Dockerfile
LABEL com.abc.image.name='xyz'
      com.abc.image.tag='latest'
Dockerfile:2:1 unexpected 'c' expecting space, "\t", "ONBUILD", "FROM", "COPY", "RUN", "WORKDIR", "ENTRYPOINT", "VOLUME", "EXPOSE", "ENV", "ARG", "USER", "LABEL", "STOPSIGNAL", "CMD", "SHELL", "MAINTAINER", "ADD", "#", "HEALTHCHECK" or end of input
```
With backslash at the end of continuing line
```
$ cat Dockerfile; hadolint Dockerfile
LABEL com.abc.image.name='xyz' \
      com.abc.image.tag='latest'
$
```
More details in [LABEL best practicies](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#label).
